@startuml
'https://plantuml.com/class-diagram

interface DataBase{

+ connect()
+query();
+ close()
}

class MYSQLDATABASE extends DataBase{
}
class ORACLEDATABASE extends DataBase{
}
class DatabaseFactory{
}
DatabaseFactory o...>DataBase
@enduml